config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'users#index'
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create]
    end
  end
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show] do
        resources :posts, only: [:index, :show] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.admin?
      can :manage, :all
    else
      can :read, :all
      can :manage, Post, author_id: user.id
      can :manage, Comment, author_id: user.id

    end
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_comments_counter

  private

  def update_comments_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_likes_counter

  private

  def update_likes_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  after_save :update_posts_counter

  validates :title, presence: true, length: { in: 1..250 }
  validates :comments_counter, :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_five_comments
    comments.last(5)
  end

  private

  def update_posts_counter
    author.update(posts_counter: author.posts.count)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy

  validates :name, presence: true, length: { in: 3..25 }
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def admin?
    role == 'admin'
  end

  def recent_three_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/v1/application_controller.rb
class Api::V1::ApplicationController < ActionController::API
  respond_to :json
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < Api::V1::ApplicationController
  before_action :set_post, :set_user

  def index
    comments = Post.find(params[:post_id]).comments
    render json: comments, status: :ok
  end

  def create
    comment = Comment.new(comment_params)
    if comment.save
      render json: comment, status: :created
    else
      render json: { errors: comment.errors }, status: :unprocessable_entity
    end
  end

  private

  def set_post
    @post_id = Post.find(params[:post_id])
  end

  def set_user
    @user_id = User.find(params[:user_id])
  end

  def comment_params
    params.require(:comment).permit(:text).merge(post_id: @post_id.id, author_id: @user_id.id)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < Api::V1::ApplicationController
  def index
    posts = Post.where(author_id: params[:user_id])
    render json: posts, status: :ok
  end

  def show
    post = Post.where(id: params[:id])
    render json: post, status: :ok
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::ApplicationController
  def index
    users = User.all.order(created_at: :asc)
    render json: users, status: :ok
  end

  def show
    user = User.find(params[:id])
    render json: user, status: :ok
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  before_action :update_allowed_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user|
      user.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |user|
      user.permit(:name, :bio, :email, :password, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  def create
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.author = current_user
    @comment.post = @post

    if @comment.save
      redirect_to user_post_path(@user, @post)
    else
      render 'posts/show'
    end
  end

  def destroy
    @comment = Comment.find(params[:id]).destroy

    respond_to do |format|
      format.html { redirect_to user_posts_path(current_user), notice: 'Comment successfully destroyed.' }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @like = Like.new
    @like.author = current_user
    @like.post = @post
    if @like.save
      redirect_to user_post_path(@user, @post)
    else
      render 'posts/show'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments, :author)
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
    @comments = @post.comments
    @comments = @post.comments.includes([:author])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user

    if @post.save
      redirect_to user_posts_path(current_user)
    else
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to user_path(current_user), notice: 'Post destroyed successfully' }
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order(created_at: :asc)
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_user_helper.rb
module BlogUserHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<div>
  <%= form_with model: Comment, url: user_post_comments_path(@user, @post), class: "contents" do |form| %>
    <%= form.label 'Add Comment' %>
    <%= form.text_area :text, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    <%= form.submit "Create Comment", class: "rounded-lg mt-3 py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  <% end %>
</div>

app/views/likes/_form.html.erb
<div>
  <%= form_with model: Like, url: user_post_likes_path(@user, @post), class: "contents" do |form| %>
    <%= form.submit "👍", class: "rounded-lg ml-2 mt-6 py-1 px-1 text-white inline-block font-medium text-xs px-3 bg-blue-200 text-red-800 rounded-full cursor-pointer" %>
  <%end%>
</div>

app/views/posts/_form.html.erb
<%= form_with model: Post, url: user_posts_path, class: "contents" do |form| %>
  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :text %>
    <%= form.text_area :text, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="inline">
    <%= form.submit "Create Post", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/posts/_posts.html.erb
<% if current_user %>
      <h2 class="mt-3">Welcome <%= current_user.name %></h2>
      <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "bg-red-400 hover:bg-red-700 text-white font-medium py-2 px-4 rounded focus:outline-none focus:shadow-outline pointer-events-auto", 'data-ripple-light': true, data: { turbo: false } %>
<% end %>
<div class="container">
  <% user.each do |user| %>
    <%= link_to user_path(user) do%>
      <div class="flex mx-10 my-5 items-center justify-center card bg-white p-6 shadow-md rounded-lg ">
        <div class="mx-5">
          <img src="<%= user.photo %>" alt="img" class="h-40 w-50 rounded-full object-cover"/>
        </div>
        <div class="w-2/3 pl-4 flex justify-between">
          <h2 class="text-lg text-center font-medium"><%= user.name %></h2>
          <span class="text-sm items-end mt-12">Number of posts: <%=user.posts.count%></span>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/posts/_single_post.html.erb
<%@user.recent_three_posts.each do |post|%>
  <%= link_to user_post_path(@user, post) do %> 
    <div class="flex flex-col border mt-5 mb-5 p-3 ">
      <h3 class="mt-2 mb-2"><%=post.title%> #<%=post.id%></h3>
      <div class="flex justify-between">
        <p class="mt-2 mb-2"><%=post.text%></p>
        <span>Comments: <%=post.comments_counter%> Likes: <%=post.likes_counter%></span>
      </div>
    </div>
  <%end%>
<%end%>

app/views/posts/index.html.erb
<div>
  <h1 class="flex justify-center p-5">All Posts</h1>
  <%= render 'shared/root'%>
  <%= render 'users/profile', user: @user%>
  <%@user.posts.each do |post|%>
    <%= link_to user_post_path(@user, post) do%>
      <div class="flex flex-col border mt-5 mb-1 pl-3 ">
        <h3 class="mt-2 mb-2"><%=post.title%> #<%=post.id%></h3>
        <div class="flex justify-between  p-2">
        <%end%>
        <p class="mt-2 mb-2"><%=post.text%></p>
        <span>💬 <%=post.comments_counter%> 👍 <%=post.likes_counter%>
        </span>
        <%if can? :destroy, post %>
          <%= link_to "🗑", user_post_path(@user, post), 
          data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, 
          class: "bg-red-500 hover:bg-red-700 text-white font-bold py-1 px-1 rounded" 
          %>
        <% end %>
      </div>
    </div>
    <div class="border pl-3 mb-5">
      <%post.recent_five_comments.each do |comment|%>
        <div class="flex justify-between mt-2 mb-2">
          <p><%=comment.author.name%>: <%=comment.text%></p>
          <% if can? :destroy, comment %>
            <%= link_to "🗑", user_post_comment_path(@user, post, comment),
          data: { turbo_method: :delete, turbo_confirm: "Are you  sure?"},
          class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-2 rounded" 
          %>
          <% end %>
        </div>
      <%end%>
    </div>
  <%end%>
</div>

app/views/posts/new.html.erb
<div class="container">
  <h2>Add New Post</h2>
  <%= render 'posts/form' %>
</div>

app/views/posts/show.html.erb
<div >
  <h1 class="p-5">Post descriptions</h1>
  <%= render 'shared/root'%>
  <div class="flex flex-col">
    <div class= "flex flex-col border mt-5 mb-5 p-5">
      <div class="flex justify-between">
        <h3 class="text-lg font-medium"><%=@post.title%> #<%=@post.id%> by <%=@post.author.name%></h3>
        <span class="text-sm items-end mt-8">Comments: <%=@post.comments_counter%> Likes: <%=@post.likes_counter%></span>
        <%= render 'likes/form'%>
      </div>
      <p class="text-sm items-end mt-8"><%=@post.text%></p>
    </div>
    <div class="border pl-3 mb-5">
      <%@comments.includes(:author).each do |comment|%>
        <div class="flex justify-between mt-2 mb-2">
          <p><%=comment.author.name%>: <%=comment.text%></p>
          <%if can? :destroy, comment%>
            <%= link_to "🗑", user_post_comment_path(comment.author, @post, comment),
          data: { turbo_method: :delete, turbo_confirm: "Are you  sure?"},
          class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-2 rounded" 
          %>
          <% end %>
        </div>
      <%end%>
    </div>
    <%= render 'comments/form'%>
  </div>
</div>

app/views/users/_all_posts.html.erb
 <div class="flex items-center justify-center mt-5 mb-5 p-3 ">
  <%=link_to user_posts_path(@user) do%>
    <button class="bg-blue-500 p-3 rounded-lg text-white mx-auto my-auto">See all posts</button>
  <%end%>
</div>

app/views/users/_create_post.html.erb
<div class="flex items-center justify-center mt-5 mb-5 p-3 ">
  <%=link_to new_user_post_path(@user) do%>
    <button class="bg-blue-500 p-3 rounded-lg text-white mx-auto my-auto">Create Post</button>
  <%end%>
</div>

app/views/users/_profile.html.erb
<div class="flex items-center justify-center card bg-white p-6 shadow-md rounded-lg ">
  <div class="mx-5">
    <img src="<%= user.photo %>" alt="img" class="h-40 w-50 rounded-full object-cover"/>
  </div>
  <div class="w-2/3 pl-4 flex justify-between">
    <h2 class="text-lg text-center font-medium"><%= user.name %></h2>
    <span class="text-sm items-end mt-12">Number of posts: <%=user.posts.count%></span>
  </div>
</div>
  

app/views/users/_user_bio.html.erb
<div class=" container d-flex flex-column border justify-content-start p-4 mt-5 mb-5">
  <h3>Bio</h3>
  <p><%=@user.bio%></p>
</div>

app/views/users/index.html.erb
<div class="container">
  <h1>All Posts</h1>
  <%= render 'posts/posts', user: @users%>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div>
  <h1 class="flex justify-center p-5">User Posts</h1>
  <%= render 'shared/root'%>
  <%= render 'users/profile', user: @user%>
  <%= render 'users/user_bio'%>
  <%= render 'posts/single_post'%>
  <div class="flex justify-between">
    <%= render 'users/all_posts'%>
    <%if current_user.id === @user.id%>
      <%= render 'users/create_post'%>
    <% end %>
  </div>
</div>